version: "3.9"
services:
       webapp:
              tty: true
              restart: unless-stopped
              container_name: weather-app-angular-dev
              build:
                     context: .
                     dockerfile: Dockerfile
              ports:
                     - "4200:4200"
              volumes:
                     - /app/node_modules
                     - .:/app
                     - node_modules:/app/node_modules
volumes:
       webapp:
              driver: local
       node_modules:
              driver: local
              driver_opts:
                     type: none
                     o: bind
                     device: ./node_modules
