version: "3.9"
services:
       webapp:
              container_name: weather-app-angular-build
              build:
                     context: .
                     dockerfile: Dockerfile
              volumes:
                     - /app/node_modules
                     - .:/app
volumes:
       webapp:
              driver: local
